### PR TITLE
Rebuild for AARCH64

### PR DESCRIPTION
**Pull request by hmaarrfk**
Try to trigger drone
@conda-forge-admin please rerender
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@mariusvniekerk can you merge to see if this enables drone-ci?

**Comment by mariusvniekerk** [comment]
Odds are we need to go do something on drone. It's a tad flaky at times.

**Comment by hmaarrfk** [comment]
The previous builds did not have any checks run on drone either.

So chances are that drone will build now.

**Comment by hmaarrfk** [comment]
Could we try merging this at least?

It would help: https://github.com/conda-forge/freeglut-feedstock/pull/19

If it doesn't help, we can maybe move to azure.

**Pull request closed without merging**
