### PR TITLE
Fix migrator (cos7 updates)

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The graphics has changed in cos7. Things have moved around a bit.
Not all of these deps are in for the cos7 arches, so we'll need to work through them.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
closes #10

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
some missing deps added to the migrator:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/427

**Comment by jayfurmanek** [comment]
@mariusvniekerk @looooo  @CJ-Wright  @hmaarrfk
This one is working now.

**Comment by jayfurmanek** [comment]
FYI @bgruening

**Comment by jayfurmanek** [comment]
FYI @xhochy

**Comment by hmaarrfk** [comment]
seems that many CDTs were missing. awesome work.

Hopefully this should fix the upgrade!

**Comment by jayfurmanek** [comment]
There might be a better way to update config.guess (download script perhaps?). I just added a patch to diff it up to the latest.

**Comment by jayfurmanek** [comment]
Hmm. Who should review?
@bgruening You're listed as maintainer. Can you take a look?

**Comment by jayfurmanek** [comment]
closes #10

**Comment by looooo** [comment]
any ideas why drone-ci wasn't triggered for this merge?

**Comment by hmaarrfk** [comment]
not sure, but i triggered it https://github.com/conda-forge/libglu-feedstock/pull/16

**Pull request merged**
